=== pypi-data/pypi-mirror-39/packages/beat.core/beat.core-1.7.0.zip/beat.core-1.7.0/beat/core/schema/experiment/2.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Experiment v2 descriptor",
  "description": "This schema defines the properties of a v2 experiment",

  "type": "object",

  "properties": {

    "description": { "$ref": "../common/1.json#/definitions/description" },

    "datasets": {
      "$ref": "common.json#/definitions/datasets"
    },

    "blocks": {
      "$ref": "common.json#/definitions/blocks"
    },

    "loops": {
      "type": "object",
      "patternProperties": {
        "^[a-zA-Z_][a-zA-Z0-9_-]*$": { "$ref": "#/definitions/loop" }
      },
      "uniqueItems": true,
      "additionalProperties": false
    },

    "analyzers": {
      "$ref": "common.json#/definitions/analyzers"
    },

    "globals": {
      "$ref": "common.json#/definitions/globals"
    },

    "schema_version": { "$ref": "../common/1.json#/definitions/version" }

  },

  "required": [
    "datasets",
    "blocks",
    "analyzers",
    "globals"
  ],

  "additionalProperties": false,

  "definitions": {

    "loop": {
      "type": "object",
      "properties": {
        "algorithm": { "$ref": "../common/1.json#/definitions/reference" },
        "parameters": { "$ref": "common.json#/definitions/parameter_set" },
        "inputs": { "$ref": "common.json#/definitions/connection_map" },
        "queue":  { "$ref": "common.json#/definitions/queue" },
        "environment":  { "$ref": "common.json#/definitions/environment" },
        "nb_slots": { "$ref": "common.json#/definitions/slots" }
      }
    }

  }

}

=== pypi-data/pypi-mirror-39/packages/beat.core/beat.core-1.7.0.zip/beat.core-1.7.0/beat/core/test/prefix/experiments/user/user/inputs_mix/3/test2.json
{
    "datasets": {
        "integers1": {
            "database": "integers_db/1",
            "protocol": "two_sets",
            "set": "double"
        },
        "integers2": {
            "database": "integers_db/1",
            "protocol": "two_sets",
            "set": "triple"
        }
    },
    "blocks": {
        "echo": {
            "algorithm": "user/integers_add/1",
            "parameters": {
            },
            "inputs": {
                "in_data": "in"
            },
            "outputs": {
                "out_data": "out"
            }
        },
        "operation": {
            "algorithm": "user/sum_over_channels/2",
            "parameters": {
            },
            "inputs": {
                "a": "a",
                "b": "b",
                "c": "c"
            },
            "outputs": {
                "sum": "result"
            }
        }
    },
    "analyzers": {
        "analysis": {
            "algorithm": "user/integers_analysis/1",
            "parameters": {
            },
            "inputs": {
                "input": "input"
            }
        }
    },
    "globals": {
        "environment": {
            "name": "Python 2.7",
            "version": "1.3.0"
        },
        "queue": "queue"
    }
}
